[build]
  command = "npm run build"
  functions = ".netlify/functions/"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/redirect"

[[redirects]]
  from = "/:code"
  to = "/.netlify/functions/redirect?code=:code"
  status = 200
  force = true
